[project]
name = "compilanceqapipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "azure-identity>=1.25.3",
    "azure-monitor-opentelemetry>=1.8.10",
    "azure-search-documents>=12.0.0",
    "azure-storage-blob>=12.30.3",
    "fastapi>=0.141.1",
    "firecrawl-py>=4.44.0",
    "langchain>=1.4.2",
    "langchain-azure-ai>=1.2.10",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.6",
    "langgraph>=1.2.12",
    "langsmith>=0.14.1",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "pandas>=3.0.6",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.1.1",
    "streamlit>=1.64.0",
    "uvicorn>=0.54.0",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
compilanceqapipeline = "compilanceqapipeline:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
